import React from 'react';
import { useApp } from '../../context/AppContext';
import { TripCardPreview } from './TripCardPreview';
import { Sparkles, User } from 'lucide-react';

export const ChatMessage = ({ message }) => {
  const { sendChatMessage } = useApp();
  const isAi = message.isAi;

  return (
    <div className={`flex gap-3 max-w-2xl ${isAi ? 'mr-auto' : 'ml-auto flex-row-reverse'}`}>
      {/* Avatar */}
      <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 shadow-xs ${
        isAi ? 'bg-primary text-white' : 'bg-secondary text-white'
      }`}>
        {isAi ? <Sparkles className="w-4 h-4 text-secondary-fixed-dim" /> : <User className="w-4 h-4" />}
      </div>

      {/* Message Bubble */}
      <div className="space-y-2">
        <div className={`p-4 rounded-2xl text-sm leading-relaxed ${
          isAi 
            ? 'bg-surface-container-lowest text-on-surface ambient-shadow border border-outline-variant/30 rounded-tl-xs' 
            : 'bg-primary text-white rounded-tr-xs shadow-sm'
        }`}>
          <div className="flex items-center justify-between gap-4 mb-1">
            <span className={`text-[11px] font-bold ${isAi ? 'text-primary' : 'text-secondary-fixed-dim'}`}>
              {message.sender}
            </span>
            <span className={`text-[10px] ${isAi ? 'text-outline' : 'text-white/60'}`}>
              {message.timestamp}
            </span>
          </div>

          <p className="whitespace-pre-line text-xs md:text-sm">{message.text}</p>
        </div>

        {/* Itinerary Preview Card if generated by AI */}
        {isAi && message.generatedTrip && (
          <TripCardPreview trip={message.generatedTrip} />
        )}

        {/* Suggested Follow-up Pills */}
        {isAi && message.suggestedPills && message.suggestedPills.length > 0 && (
          <div className="flex flex-wrap gap-1.5 pt-1">
            {message.suggestedPills.map((pill, idx) => (
              <button
                key={idx}
                onClick={() => sendChatMessage(pill)}
                className="text-[11px] font-medium bg-surface-container-low hover:bg-surface-container text-on-surface-variant hover:text-primary px-3 py-1 rounded-full border border-outline-variant/40 transition active:scale-95 shadow-xs"
              >
                {pill}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};
