import React, { createContext, useContext, useState, useEffect } from 'react';
import { apiService } from '../services/api';

const AppContext = createContext();

export const AppProvider = ({ children }) => {
  const [activeTab, setActiveTab] = useState('landing'); // 'landing' | 'chat' | 'itinerary' | 'voting'
  const [activeTripId, setActiveTripId] = useState('active');
  const [itinerary, setItinerary] = useState(null);
  const [destinations, setDestinations] = useState([]);
  const [votingData, setVotingData] = useState({ candidates: [], activityFeed: [] });
  const [travelerProfile, setTravelerProfile] = useState({});
  const [chatMessages, setChatMessages] = useState([
    {
      id: 1,
      sender: "Venture Concierge",
      timestamp: "10:30 AM",
      text: "Namaste! Welcome to Venture AI. I'm your AI Travel Concierge. Tell me where you are dreaming of traveling, and let's craft an unforgettable bespoke journey together!",
      isAi: true
    }
  ]);
  const [loading, setLoading] = useState(false);
  const [toastMessage, setToastMessage] = useState(null);

  const showToast = (msg) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3500);
  };

  // Load initial data from FastAPI backend
  useEffect(() => {
    async function loadInitialData() {
      try {
        const [itineraryRes, destinationsRes, votingRes] = await Promise.all([
          apiService.getItinerary('active').catch(() => null),
          apiService.getDestinations().catch(() => []),
          apiService.getVotingData('active').catch(() => ({ candidates: [], activityFeed: [] }))
        ]);
        if (itineraryRes) setItinerary(itineraryRes);
        if (destinationsRes) setDestinations(destinationsRes);
        if (votingRes) setVotingData(votingRes);
      } catch (err) {
        console.error("Initialization error:", err);
      }
    }
    loadInitialData();
  }, []);

  const sendChatMessage = async (text) => {
    if (!text || !text.trim()) return;

    const userMsg = {
      id: Date.now(),
      sender: "You",
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      text: text.trim(),
      isAi: false
    };

    setChatMessages(prev => [...prev, userMsg]);
    setLoading(true);

    try {
      const response = await apiService.sendChatMessage(text);
      const aiMsg = {
        id: Date.now() + 1,
        sender: response.sender || "Venture Concierge",
        timestamp: response.timestamp || new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        text: response.text,
        suggestedPills: response.suggestedPills,
        generatedTrip: response.generatedTrip,
        isAi: true
      };
      setChatMessages(prev => [...prev, aiMsg]);
      
      // Update real-time traveler profile state if returned from MongoDB/LLM
      if (response.currentProfile && Object.keys(response.currentProfile).length > 0) {
        setTravelerProfile(response.currentProfile);
      }

      // Update dynamic itinerary if generated by the LLM
      if (response.generatedTrip) {
        setItinerary(response.generatedTrip);
        if (response.generatedTrip.id) {
          setActiveTripId(response.generatedTrip.id);
        }
      }
    } catch (err) {
      console.error("Chat error:", err);
      showToast(err.message || "Could not reach backend service.");
    } finally {
      setLoading(false);
    }
  };

  const castVote = async (candidateId, voteType) => {
    try {
      const res = await apiService.castVote(activeTripId, candidateId, voteType);
      setVotingData({
        candidates: res.candidates,
        activityFeed: res.activityFeed
      });
      showToast(`Vote recorded! Group consensus: ${res.candidate.consensusScore}%`);
    } catch (err) {
      console.error(err);
      showToast("Error submitting vote.");
    }
  };

  const addActivity = async (dayNumber, activityData) => {
    try {
      const res = await apiService.addActivity(activeTripId, dayNumber, activityData);
      setItinerary(res.itinerary);
      showToast("New activity stop added to your itinerary!");
    } catch (err) {
      console.error(err);
      showToast("Error adding activity stop.");
    }
  };

  return (
    <AppContext.Provider
      value={{
        activeTab,
        setActiveTab,
        activeTripId,
        itinerary,
        setItinerary,
        destinations,
        votingData,
        travelerProfile,
        chatMessages,
        sendChatMessage,
        castVote,
        addActivity,
        loading,
        setLoading,
        toastMessage,
        showToast
      }}
    >
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => useContext(AppContext);
